// <auto-generated />
using AspBase.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspBase.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250101000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("AspBase.Api.Domain.Entities.Image", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Height").HasColumnType("integer");
            b.Property<string>("ImageHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("ImagePath").HasColumnType("text");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Width").HasColumnType("integer");
            b.HasKey("Id");
            b.ToTable("images", (string)null);
        });

        modelBuilder.Entity("AspBase.Api.Domain.Entities.User", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
            b.Property<string>("Avatar").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<string>("FirstName").HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<bool>("IsCustomer").HasColumnType("boolean");
            b.Property<bool>("IsStaff").HasColumnType("boolean");
            b.Property<bool>("IsSuperuser").HasColumnType("boolean");
            b.Property<bool>("IsValidate").HasColumnType("boolean");
            b.Property<string>("LastName").HasMaxLength(255).HasColumnType("character varying(255)");
            b.Property<DateTime?>("LastLogin").HasColumnType("timestamp with time zone");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<bool>("ReceiveNews").HasColumnType("boolean");
            b.Property<string>("RestoreCode").HasMaxLength(8).HasColumnType("character varying(8)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("users", (string)null);
        });
#pragma warning restore 612, 618
    }
}
